### ISSUE TITLE
Review clang-tidy checks

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#1125]
## Description

A lot of checks have been added since we started using clang-tidy.

We should review them and add the pertinent ones to our config

**Related epic/story/task**: 

## Subtasks 

- [ ] `v11` - https://releases.llvm.org/11.0.0/tools/clang/tools/extra/docs/ReleaseNotes.html#new-checks
- [ ] `v12` - https://releases.llvm.org/12.0.0/tools/clang/tools/extra/docs/ReleaseNotes.html#new-checks
- [ ] `v13` - https://releases.llvm.org/13.0.0/tools/clang/tools/extra/docs/ReleaseNotes.html#new-checks
- [ ] `v14` - https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/ReleaseNotes.html#new-checks
- [ ] `v15` - https://releases.llvm.org/15.0.0/tools/clang/tools/extra/docs/ReleaseNotes.html#new-checks
