### ISSUE TITLE
[Task] - CI - add delta to bootloader + os  base/head comparison 

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#1144]
## Description

In the current file comparison analysis report, the bootloader + os stats are shown without the delta between base and head.

The data is shown in the summary but does not take into account the actual memory space reserved for the bootloader and os, so the delta and flash/ram available percentages are not accurate.

**Related epic/story/task**: 

## Subtasks 

- [x] add total flash delta
- [x] add static ram delta
- [x] add base/head values
