### ISSUE TITLE
[Task] - tests - hardware - CoreIMU/LSM6DSOX

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#1149]
## Description

Following #1128, we would like to separate:

- component tests, focused on LSM6DSOX, to make sure it works properly w/ I2C
- functional tests, focused on CoreIMU, to make sure that, the components behave as expected, w/ inputs and outputs

**Related epic/story/task**: 

- #1128 

## Subtasks 

- [x] separate LSM6DOSX from CoreIMU
- [x] create two directories (to have two .bin files at the end)
- [x] find a way to test LSM6DSOX is working properly after `init()`
- [x] remove LSM6DSOX tests from CoreIMU to focus on functional testing there

**Comment by ladislas** [comment]
closed by [7816e6d](https://github.com/leka/LekaOS/commit/7816e6dfc7f6c24e11e8e4c993dad93fce2df857)
