### ISSUE TITLE
[Story] - Code Analysis - Setup nanobench to assess code performance

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#1232]
## Description

It's really hard to assess code performance just by watching the code run and looking at logs.

Most of the time it's necessary to use external tools.

https://github.com/martinus/nanobench is one of them, that could be used to monitor code performance/speed for critical parts of our system.

Monitoring performance fluctuations between commits is an important aspect of code quality.

**Related epic/story/task**: 

## Subtasks 

- [ ] setup nanobench
- [ ] make functional example
- [ ] implement CI feedback for pull requests
- [ ] decide which part of code are critical
- [ ] list use cases we want to monitor
