### ISSUE TITLE
🐛  [Bug] - Robot crashes when working with Autonomous Activities

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#1311]
## Description

Following #1273, the robot crashes when working with autonomous activities, especially when an activity is exited using the Dice card.

**Related epic/story/task**: 

## Subtasks 

- [x] https://github.com/leka/LekaOS/pull/1303
- [ ] https://github.com/leka/LekaOS/pull/1310
- [ ] todo - find real fix
