### ISSUE TITLE
[Task] - Implement custom targets

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#21]
## Description

For development and later for production phases, we need to implement custom targets to make the process easier

**Related epic/story**: #26 

## Subtasks 

- [x] ~~Leka_v1_DEV~~ DISCO_ORIGINAL - using the [32F769IDISCOVERY](https://www.st.com/en/evaluation-tools/32f769idiscovery.html) while we wait for the mainboard
- [x] DISCO_MODIFIED - based on DISCO_ORIGINAL but with removed features
- [x] DISCO_IOC - generated from .ioc file with the same features removed than DISCO_MODIFIED
- [x] ~~Leka_v1_PROD~~ LEKA_V1.0_DEV - for our development mainboard
- ~~[ ] Leka_v1_DEV_BLE - using the [P-NUCLEO-WB55](https://www.st.com/en/evaluation-tools/p-nucleo-wb55.html)~~
