### ISSUE TITLE
[Task] - Screen JPEG decode using DMA

### ISSUE THREAD

**Issue by Madour** [leka/LekaOS#273]
## Description

Right now, image and video display is done using JPEG decoding in "polling" mode, which is very slow (~100ms for 1 image).
The better way is to use JPEG decoding with DMA.

## Subtasks

- [x] Display an image using `HAL_JPEG_Decode_DMA`
- [x] Play a video using `HAL_JPEG_Decode_DMA`
- [x] Integrate decode_dma.c functions in video driver
- [x] Optimize performance
    - [x] Double frame buffer
    - [x] #284
    - [x] Use DSI in adapted command mode -> frame buffer in GRAM -> faster data transfer = better fps
