### ISSUE TITLE
[Task] - Robot software specifications for investigation day 

### ISSUE THREAD

**Issue by YannLocatelli** [leka/LekaOS#34]
## Description

Create a document to gather all specifications of the behavior of the robot. Each component of it must be tested at its maximum in order to have the worst situation for investigation day. Values has to be clear.

**Related epic/story**:  #36 

## Subtasks 

- [x] Draft with an overview of behavior for each component @YannLocatelli 
- [x] First meeting to check the draft @YannLocatelli @ladislas 
- [x] Create the document based on the draft and feedbacks @YannLocatelli 
- [x] Add values (theoretical)
- [x] Test them (if possible)
- [x] Contact the design offices
- [x] Adapting the document with feedbacks
- [x] Update values (practical)
- [x] Test them again (if possible)
- [x] Final meeting to check the document
