### ISSUE TITLE
[Task] - Watchdog - Compare between thread and ticker

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#48]
## Description

The current version of the watchdog uses a thread.

@YannLocatelli proposed an alternative solution using a ticker which might be more light weight here: https://github.com/leka/LekaOS/issues/17#issuecomment-702851437

```cpp
#include "mbed.h"

Ticker kicker;

void watchdogKick()
{
    Watchdog::get_instance().kick();
}

int main()
{
    printf("\n\nDemonstration of watchdog in case of error (happens in 10s).\n");

    const uint32_t TIMEOUT_MS = 5000;
    Watchdog &watchdog = Watchdog::get_instance();
    watchdog.start(TIMEOUT_MS);

    kicker.attach_us(watchdogKick, 1000);
    
    ThisThread::sleep_for(10s);
    error("This is a reason why watchdog exists. Restarting in 5000ms...\n");
    
    return 0;
}
```

**Related epic/story**:  #19 

## Subtasks 

- [ ] create two examples, one with a thread and the other with a timer
- [ ] test them with fatal errors and while loops
- [ ] compare size or executable
