### ISSUE TITLE
[Task] - Screen - Exploration to use JPEG

### ISSUE THREAD

**Issue by YannLocatelli** [leka/LekaOS#77]
# Ecran - valider le jpeg

## Description

Display a JPEG image on the screen connected on Leka board.

### Etat initial

Journée d’investigation:

* LekaScreen avec la structure pour la journée d’investigation qui appelle LekaLCD
* LekaLCD, code de Modar avec l’animation du cube

## Tasks

- [x] Récupération du fichier JPEG
	- [x] Utilisation de la carte SD (conversion de DISCO-SDMMC vers LEKA-SPI)
		- [x] Add "SD" in `components_add` in custom_target.json file
		- [x] Add pins in mbed_app.json file
		- [x] Implement SD and FATFileSystem
			- [x] Test - With mbed (SDBlockDevice, FATFileSystem) ✅ 
			- [x] Test - In ST example (FATFS) ❌ 
	- [x] Ouverture fichier JPEG
		- [x] Test - With mbed (`fopen` from FILE) ❌ 
		- [x] Test - In ST example (`f_open` from FIL) ✅ 
		- [x] Vérification de la taille fichier
- [ ] Etat du code de Modar sous mbed
	- [x] Test - Cube animation ✅ 
	- [x] Test - Image en .h ✅ 
		- [x] Trouver le code avec le bon commit → [#1f3d067](https://github.com/leka/LekaOS_Explorations/tree/1f3d0672e7ea937eac6396518bf0f7df6af2a160)
		- [x] Récupérer les images en .h (eye + mouth)
		- [x] Implémenter le code dans celui de la journée d’investigation
	- [x] Test - Image en JPEG ❌ 
		- [x] Implémenter les libs nécessaires
			- [x] `decode_dma`
			- [x] `jpeg_utils`
			- [x] `jpeg_utils_conf`
			- [x] `BSP_DISCO_F769NI`
		- [x] \(1) Résoudre **ERROR** ([lien](https://github.com/leka/LekaOS_Explorations/blob/6033ce9d8a6ef79011787ca07cbfd03bd95c8286/LKExp-LCD-Mbed_JPEG_Display/src/main.cpp#L54)) durant l’appel de la fonction `JPEG_Decode_DMA` ✅ 
			- [x] Localiser l’erreur  
			`JPEG_Decode_DMA` (`decode_dma`)   
		   → `HAL_JPEG_Decode_DMA` (`stm32f7xx_hal_jpeg`)  
		   → `JPEG_DMA_StartProcess` (`stm32f7xx_hal_jpeg`)  
		   at `hjpeg->hdmain->XferCpltCallback = JPEG_DMAInCpltCallback;`
			- [x] Identifier les sources
				- [x] Test - `hjpeg` mal instancié   
				`HAL_JPEG_MspInit` (`stm32f7xx_hal_jpeg`) vide et en __weak
			- [x] Appliquer des solutions
				- [x] Remplacer par celui proposé dans l’exemple ST → [lien](https://github.com/STMicroelectronics/STM32CubeF7/blob/master/Projects/STM32F769I-Discovery/Examples/JPEG/JPEG_DecodingUsingFs_DMA/Src/stm32f7xx_hal_msp.c) ✅ 
		- [ ] \(2) Résoudre **NOTHING HAPPENS** dans le `JPEG_Decode_DMA`
			- [x] Localiser l’erreur  
			`JPEG_Decode_DMA` (`decode_dma`)   
		   → `HAL_JPEG_Decode_DMA` (`stm32f7xx_hal_jpeg`)  
		   → `JPEG_DMA_StartProcess` (`stm32f7xx_hal_jpeg`)  
		   at `JPEG_ENABLE_DMA(hjpeg, JPEG_DMA_IDMA | JPEG_DMA_ODMA);`  
			- [ ] Identifier les sources
				- [ ] Macro does not work correctly
			- [x] Appliquer des solutions
				- [x] Test - Remplacer par `MODIFY_REG(hjpeg->Instance->CR, ((JPEG_DMA_IDMA | JPEG_DMA_ODMA) & JPEG_DMA_MASK), 1UL);`
		- [ ] \(3) Résoudre **NOTHING HAPPENS** dans le do{...}while
			- [x] Localiser l’erreur  
			`JPEG_InputHandler` (`decode_dma`)   
			- [ ] Identifier les sources
				- [ ] `Jpeg_IN_BufferTab` always FULL
				- [ ] `JPEG_OutputHandler` never FULL
			- [ ] Appliquer des solutions
	- [ ] Test - Video en AVI ([lien](https://github.com/leka/LekaOS_Explorations/tree/madour-LCD-Mbed_Video_Display/LKExp-LCD-Mbed_Video_Display))
- [ ] Fusion des libs LekaScreen et LekaLCD (objectif Cube bouncing et une meilleure maîtrise des handlers)
	- [x] Récupérer les sources
		- [x] Code of Modar ([link](https://github.com/leka/LekaOS_Explorations/tree/5c209582c53ef52b3e86b901de585dbe1b8b241b/LKExp-LCD-Mbed_JPEG_Display))
		- [x] Example from ST without using JPEG ([link](https://github.com/STMicroelectronics/STM32CubeF7/tree/master/Projects/STM32F769I-Discovery/Examples/JPEG/JPEG_DecodingUsingFs_DMA))
		- [x] BSP - LCD init ([link](https://os.mbed.com/teams/ST/code/BSP_DISCO_F769NI/))
	- [x] Ajout des initialisations dans LekaScreen
		- [x] `LCDReset` → Hardware reset de ...
		- [x] `MSPInit` → HAL Initialize modules in MCU related to display process
		- [x] `DSIInit` → "Driver" Initialize DSI interface
		- [x] `LTDCInit` → "Driver" Initialize LTDC with **SDRAM (?)**
		- [x] `SDRAMInit` (in`LTDCInit`) → HAL and "Driver" Initialize of SDRAM
		- [x] `OTM8009AInit` → Driver Initialize LCD
	- [x] Configurations des initialisations selon le code de Modar (annotées avec Previously en cas de changement)
	- [x] Ajout de la partie applicative
		- [x] `LTDCLayerInit` → Configuration couche écran
		- [x] `setActiveLayer` → Désigner la couche active (2)
		- [x] `clear` → Nettoyer l’écran avec une couleur
		- [x] `drawRectangle` 
		- [x] `fillBuffer` → Transfert du dessin dans DMA2D
	- [x] Vérification des initialisations
		- [x] Résoudre **NOTHING HAPPENS** après initialisations
			- [ ] Localiser l’erreur    
			- [x] Identifier les sources
				- [x] `DSI_IO_WriteCmd` (`otm8009a`) vide et en __weak
			- [x] Appliquer des solutions
				- [x] Remplacer par la proposition de Modar → [lien](https://github.com/leka/LekaOS_Explorations/blob/6033ce9d8a6ef79011787ca07cbfd03bd95c8286/LKExp-LCD-Mbed_JPEG_Display/src/LekaLCD.cpp#L296-L303) ✅ 
		- [ ] Identifier la provenance de `hdma`
	- [x] Vérification de la partie applicative
	- [x] Image en .h
- [ ] Afficher une image JPEG
	- [x] *Récupération du fichier JPEG*
	- [x] *Fusion des libs LekaScreen et LekaLCD*
	- [ ] Identifier les sources d’inspirations
		- [x] Exemple ST (DISCO) en utilisant le DMA → [lien](https://github.com/STMicroelectronics/STM32CubeF7/tree/master/Projects/STM32F769I-Discovery/Examples/JPEG/JPEG_DecodingUsingFs_DMA)
		- [x] Exemple ST (EVAL) en utilisant le polling → [lien](https://github.com/STMicroelectronics/STM32CubeF7/tree/master/Projects/STM32F769I_EVAL/Examples/JPEG/JPEG_DecodingUsingFs_Polling)
		- [ ] Exemple ST (EVAL) en utilisant l’interrupt → [lien](https://github.com/STMicroelectronics/STM32CubeF7/tree/master/Projects/STM32F769I_EVAL/Examples/JPEG/JPEG_DecodingUsingFs_Interrupt)
		- [x] Exemple video de Modar → [lien](https://github.com/leka/LekaOS_Explorations/blob/madour-LCD-Mbed_Video_Display/LKExp-LCD-Mbed_Video_Display/src/main.cpp)
- [x] Ajout à la lib la rotation de l’écran (lié à `OTM8009A_MADCTR_MODE_LANDSCAPE` dans `otm8009a`)
- [ ] Réimplémenter `OTM8009A_Init` dans son driver, nécessite de bien définir `DSI_IO_WriteCmd`
- [ ] Répartir les différentes initialisations et partie applicative dans différentes "sous-lib"
- [ ] Schéma de la relation entre les différents modules avec le chemin du fichier JPEG dans la carte SD jusqu’à l’affichage sur l’écran
- [ ] Schéma du parcours du code selon les différents libs parcourus (vérification des fonctions vides et en __weak)
