### ISSUE TITLE
[Task] - Improve caching for github actions

### ISSUE THREAD

**Issue by ladislas** [leka/LekaOS#82]
## Description

For the moment, the caching mechanism is not that great...

**Related epic/story/task**:  #7 #81 

## Subtasks 

- [ ] try with ccache
- [ ] use mbed_app.json && custom_targets.json as hashFiles()
- [ ] cache mbed-os from curl
